### ISSUE TITLE
可以写一个详细集成这个sdk的教程不？

### ISSUE THREAD

**Issue by Torin2876** [wedxz/LNTheme#1]
如：一个新项目。怎么通过网络下载动态改变tabBar上的图片。看了半天代码了，一头雾水

**Comment by vvusu** [comment]
demo 中使用的就是网易云音乐的API ，使用他们的主题压缩包下载格式，可根据业务需要自定义方式，框架中不包含网络下载和解压的部分，只是demo 中有，你可以参照。
