### ISSUE TITLE
小小的问题

### ISSUE THREAD

**Issue by lishuailibertine** [wedxz/LNTheme#2]
为什么当时你写这个组件更新主题(整体)，用的是hashTable存储元素遍历去更新，而不用采用通知，增加观察者去更新呢？

**Comment by vvusu** [comment]
问的挺好，采用通知的方式和观察者的方式都可以做到同样的效果。而采取HashTable的方式更加方便，另外在已经比较成熟的项目中接入SDK工作量想对较小。

**Comment by lishuailibertine** [comment]
还有个功能上的小问题：根据读代码，发现图片资源的获取可以能从沙盒中获取（如果想从工程获取，需要在.json中配置(图片多的话有点麻烦)）；样式配置资源的获取工程或者沙盒都可以；如果工程的样式配置主题名字与沙盒中某主题名字命名一样的话，沙盒的样式配置解析会覆盖工程的样式配置解析结果(也不全是覆盖)；不晓得这些是当时设计成这样的吗？还有就是我这些理解对吗？谢谢作者。

**Comment by vvusu** [comment]
图片名字添加到json里暂时没有好的解决办法。现在大多使用的是Iconfont，图片相对较少了。
样式配置可以支持多Framework的子样式的配置，比如白天模式的话，配置文件可以写成多个json文件然后会组成一个配置文件也会覆盖掉重复的字段。

**Comment by aflyingfish01** [comment]
发现项目中大量使用后 性能问题比较严重 更新完成需要5s左右

**Comment by vvusu** [comment]
如果主题控件比较多的话，低端机子可能会卡的，必进是在主线程进行UI操作，你可以加上一个Loding
让它加载完成后再操作别的。（没有好的解决办法，如果有更好的解决办法欢迎告知）
