### ISSUE TITLE
能不能指定某一个主题

### ISSUE THREAD

**Issue by lzc1022** [wedxz/LNTheme#3]

**Comment by lishuailibertine** [comment]
@wedxz 博主我写了个换肤的工具你瞅瞅，有些直接用你的了，抛弃你当时用hashMap的方式(在项目中使用感觉渲染效率太差了)；给点意见啊=. =.[换肤工具](https://github.com/lishuailibertine/SLSkinManage) ,感觉想法独特的话给个小星星啊

**Comment by vvusu** [comment]
大概浏览了一下，写的不错，挺好的。之前的问题，可以指定主题的，本地和线上的主题都可以指定。

2018-02-09 13:59 GMT+08:00 lishuailibertine <notifications@github.com>:

**Comment by wedxz** [comment]
为什么当时你写这个组件更新主题(整体)，用的是hashTable存储元素遍历去更新，而不用采用通知，增加观察者去更新呢？
这个问题进行回复：
因为看到别人都用通知和监听做，都说想用HashTable 试试，我就用HashTable
试试的做了，效果还行。工程就用的这个，你们所说的性能问题，我没怎么越到过，可以下载“华尔街见闻APP 试一下主题切换” 。

2018-02-09 13:59 GMT+08:00 lishuailibertine <notifications@github.com>:

**Comment by vvusu** [comment]
你说的渲染效率太差是什么机子上测试的，大概内存使用主题的对象是多少个？，因为我这边使用正常没怎么遇见过效率差的时候

**Comment by lishuailibertine** [comment]
@wedxz 真机上整个hashTable渲染大概3到4秒的样子，对象的话我倒是没打断点看过，因为项目比较急也没关心太多了。忘说了是在6上看的。

**Comment by vvusu** [comment]
渲染时间和注册主题对象的个数是有直接关系的。这个和hastable 使用没有关系的。你写的通知也是一样的同时监听，同时主线程操作。

**Comment by lishuailibertine** [comment]
@wedxz 是的，但是还是有区别的(hashTable遍历和监听的方式)，虽然都是在主线程操作；其实我也不太清楚为什么会差别那么大。确实是换成通知的方式试了下就好了许多，在低端机上我也试了。忘了我在git上有原来集成的我再看下耗时。
